### ISSUE TITLE
회원정보 API에 닉네임과 ID도 오게 해주세요

### ISSUE THREAD

**Issue by Yong4124** [DSU-POD/sikdan-api#35]
회원정보에는 닉네임을 회원정보수정 페이지는 닉네임과 ID가 오게해주세요
{result: "success", message: "회원 정보를 불러왔습니다.",…}
data
: 
{age: 23, height: 123, weight: 123, goal: "weightdecrease", allergy: ""}
message
: 
"회원 정보를 불러왔습니다."
result
: 
"success"

**Comment by pgkwon1** [comment]
@Youmin02 님이 추가 하여 해결되었습니다.
